//
//  data+entry.swift
//  Psyche
//
//  Created by Rivinis on 3/22/18.
//  Copyright © 2018 ASU. All rights reserved.
//

import Foundation
import UIKit

// array of arrays, each has: [0] question, [1], [2] ... answers, [last element]: correct answer

// psyche easy
var psyche1 = [["Q1: Psyche is the name of a/an ____ orbiting the Sun between Mars and Jupiter.",
                "Comet", "Planet", "Asteroid", "Star",
                "Asteroid"],
               ["Q2: Psyche is the first mission to a world made of ____.",
                "Rock", "Ice", "Gas", "Metal",
                "Metal"],
               ["Q3: Which US University is leading this deep-space investigation?",
                "Arizona State University", "Alabama State University", "University of Arizona", "Massachusetts Institute of Technology",
                "Arizona State University"],
               ["Q4: What year is the Psyche spacecraft scheduled to be launched?",
                "2020", "2022", "2026", "2023",
                "2022"],
               ["Q5: True or False: Psyche, the asteroid, has an irregular shape.",
                "True", "False",
                "True"],
               ["Q6: Scientists have hypothesized that Psyche's shape was caused by:",
                "Collisions", "Gravity", "Spinning forces", "All of the above",
                "Collisions"],
               ["Q7: What year is the spacecraft scheduled to arrive at the asteroid Psyche?",
                "2025", "2026", "2027", "2099",
                "2026"],
               ["Q8: Some scientists believe that Psyche could actually be:",
                "A snowball", "A dwarf planet", "A planet's core", "A moon",
                "A planet's core"],
               ["Q9: Psyche is named after the goddess of ____ in ancient Greek mythology.",
                "The night", "The dawn", "Wisdom", "The soul",
                "The soul"],
               ["Q10: Who is the principal investigator of the Psyche Mission Team?",
                "Jim Bell", "Erik Asphaug", "Lindy Elkins-Tanton", "David Bercovici",
                "Lindy Elkins-Tanton"]]

// psyche medium
var psyche2 = [["Q1: When was the Psyche Mission chosen by NASA?",
                "01/04/2017", "01/02/2017", "02/03/2017", "01/30/2017",
                "01/04/2017"],
               ["Q2: A year on the asteroid Psyche is equal to how many Earth years?",
                "One", "Three", "Five", "A hundred",
                "Five"],
               ["Q3: The full spacecraft, including the solar panels, is about the size of a/an ____.",
                "Bowling lane", "Singles tennis court", "Football field", "Olympic swimming pool",
                "Singles tennis court"],
               ["Q4: Psyche is the ____ asteroid to ever be discovered.",
                "4th", "16th", "21st", "22nd",
                "16th"],
               ["Q5: What year was Psyche the asteroid discovered?",
                "1864", "1896", "1910", "1852",
                "1852"],
               ["Q6: What is the average distance between Psyche and the Sun in astronomical units (AU)?",
                "1 AU", "2 AU", "3 AU", "0.5 AU",
                "3 AU"],
               ["Q7: True or False: Psyche and Earth orbit the Sun at the same speed.",
                "True", "False",
                "False"],
               ["Q8: Psyche is believed to be made almost entirely out of:",
                "Nickel", "Iron", "Gold and silver", "Nickel and iron",
                "Nickel and iron"],
               ["Q9: Which object is similar to Psyche in its density?",
                "A bar of steel", "A roll of aluminum foil", "A gold coin", "A German Shepherd",
                "A bar of steel"],
               ["Q10: The Psyche Mission will use new communication technology to transfer data via: ",
                "Radio", "Photons", "Snapchat", "Wi-Fi",
                "Photons"]]

// psyche hard
var psyche3 = [["Q1: What periodic element is responsible for the solar electric propulsion that Psyche will use?",
                "Nitrogen", "Xenon", "Hydrogen", "Oxygen",
                "Xenon"],
               ["Q2: How long is a day on Psyche?",
                "5 hours, 2 minutes", "4 hours, 12 minutes", "4 hours, 22 minutes", "3 hours, 57 minutes",
                "4 hours, 12 minutes"],
               ["Q3: Who discovered Psyche in 1852?",
                "Annibale de Gasparis", "Barnaba Oriani", "Giovanni Battista Donati", "Francesco de Vico",
                "Annibale de Gasparis"],
               ["Q4: When did NASA have evidence that confirmed Psyche's metal composition?",
                "2008", "2012", "2011", "2010",
                "2010"],
               ["Q5: What company is building the solar-electric propulsion chassis?",
                "General Dynamics", "Tesat Spacecom", "Space Systems Loral", "Malin Space Science Systems",
                "Space Systems Loral"],
               ["Q6: The Psyche Mission will use a/an ____ telecommunications system to measure Psyche's gravity field.",
                "X-band Radio", "P25 Radio", "Optical", "High-rate RF",
                "X-band Radio"],
               ["Q7: The team responsible for developing the Psyche Gamma Ray and Neutron Spectrometer is based at:",
                "Massachusetts Institute of Technology", "University of California", "Southwest Research Institute", "Johns Hopkins University",
                "Johns Hopkins University"],
               ["Q8: If Psyche were a perfect sphere, it would have a surface area approximately the size of:",
                "Texas", "California", "Montana", "Alaska",
                "Texas"],
               ["Q9: How much mass of the Asteroid Belt does Psyche represent?",
                "0.50%", "3%", "1%", "5%",
                "1%"],
               ["Q10: The Psyche Mission total cost (development, operations, and science) is estimated to be about:",
                "$600 Million", "$775 Million", "$950 Million", "$850 Million",
                "$850 Million"]]

// nasa easy
var nasa1 = [["Q1: From 1957 to 1975, the United States competed primarily with what country in the Space Race?",
              "China", "Soviet Union (USSR)", "Cuba", "Germany",
              "Soviet Union (USSR)"],
             ["Q2: What was the name of the successful NASA Mission to the moon?",
              "Mercury Program", "Apollo 11", "Mission Impossible", "Project Vanguard",
              "Apollo 11"],
             ["Q3: Which space vehicle is used to carry astronauts to space and back?",
              "Space Shuttle", "Rocket", "Launch Vehicle", "Satellite",
              "Space Shuttle"],
             ["Q4: Earth is the only planet where ____ is known to exist.",
              "Weather", "Air", "Water", "Life",
              "Life"],
             ["Q5: A ____ is an object that moves around a larger object.",
              "Probe", "Moon", "Satellite", "Telescope",
              "Satellite"],
             ["Q6: What is the name of the largest telescope currently orbiting Earth?",
              "Hubble", "Bubble", "Gaia", "Astrosat",
              "Hubble"],
             ["Q7: A supernova is the ____ of a star.",
              "Nebula or Birth", "Cooling", "Main Sequence", "Death explosion",
              "Death explosion"],
             ["Q8: Who was the first United States' female astronaut?",
              "Sally Ride", "Kathryn Sullivan", "Mae Jemison", "Peggy Whitson",
              "Sally Ride"],
             ["Q9: Where is Psyche the Asteroid located?",
              "Outside the Solar System", "Between Venus and Earth", "In the Asteroid Belt", "Orbiting Jupiter",
              "In the Asteroid Belt"],
             ["Q10: Psyche is the first mission to a world made of _____.",
              "Rock", "Ice", "Candy", "Metal",
              "Metal"]]

// nasa medium
var nasa2 = [["Q1: What is the name of the satellite currently orbiting Jupiter?",
              "Virgil", "Juno", "Dido", "Tanit",
              "Juno"],
             ["Q2: Which program helped prepare NASA to land on the moon?",
              "Ranger Program", "Project Mercury", "Gemini Program", "Mercury Program",
              "Gemini Program"],
             ["Q3: Planet Earth is also known to scientists as the ____ planet.",
              "Best", "Home", "Live", "Goldilocks",
              "Goldilocks"],
             ["Q4: True or False: the Earth is not a perfect sphere.",
              "True", "False",
              "True"],
             ["Q5: The number of meteorites found in ____ is equal to the number of meteorites found in the rest of the world combined.",
              "North America", "Asia", "Africa", "Antartica",
              "Antartica"],
             ["Q6: What year was the Hubble Space Telescope launched into orbit?",
              "1993", "1983", "1990", "1997",
              "1990"],
             ["Q7: NASA was created in what year?",
              "1957", "1958", "1955", "1956",
              "1958"],
             ["Q8: What year is the spacecraft scheduled to arrive at Psyche the asteroid?",
              "2025", "2028", "2027", "2026",
              "A55555"],
             ["Q9: What is the highest number of women that have been in space together at once?",
              "4", "3", "5", "2",
              "4"],
             ["Q10: True or False: You can see Earth's round shadow on the moon during a lunar eclipse.",
              "True", "True",
              "True"]]

// nasa hard
var nasa3 = [["Q1: Who was the first American in space?",
              "James A Lovell, Jr.", "Buzz Aldrin", "Alan Shepard", "Gus Grissom",
              "Alan Shepard"],
             ["Q2: What was the name of the NASA Rocket that launched humans to the moon?",
              "Delta G", "Thor-Delta", "Scout", "Saturn V",
              "Saturn V"],
             ["Q3: True or False: with GPS and satellites, scientists can measure Earth's size and shape to within a millimeter.",
              "True", "False",
              "False"],
             ["Q4: What company is partnered with NASA to develop the Robonaut?",
              "Space Systems Loral", "General Motors", "General Dynamics", "Tesat Spacecom",
              "General Motors"],
             ["Q5: Hubble transmits ____ gigabytes of science data each week back to Earth.",
              "140", "150", "120", "175",
              "140"],
             ["Q6: NASA uses solar eclipses as an opportunity to study the sun's ___.",
              "Corona", "Chromosphere", "Core", "All of the above",
              "Corona"],
             ["Q7: As of this April 2018, how many women have been in space?",
              "58", "60", "63", "57",
              "60"],
             ["Q8: Katherine Johnson's first task on the space team was to calculate the ____ for the rocket that would put the first American in space.",
              "Thrust", "Fuel Required", "Flight Path", "Altitude",
              "Flight Path"],
             ["Q9: Where is the Psyche Spacecraft scheduled to launch from?",
              "Goddard Space Flight Center", "Wallops Flight Facility", "Marshall Space Flight Center", "Kennedy Space Center",
              "Kennedy Space Center"],
             ["Q10: Who is the current NASA Administrator?",
              "Steve Jurczyk", "Krista Baquin", "Robert M Lightfoot, Jr.", "Thomas Cremins",
              "Robert M Lightfoot, Jr."]]

// space easy
var space1 = [["Q1: What is the hottest planet in the solar system?",
               "Earth", "Venus", "Saturn", "Neptune",
               "Venus"],
              ["Q2: What was the name of the successful NASA Mission to the moon?",
               "Mercury Program", "Apollo 11", "Ranger Program", "Project Vanguard",
               "Apollo 11"],
              ["Q3: One of Jupiter's most famous features is ____.",
               "The Great Red Spot", "An icy surface", "Plant life", "its love for rock music",
               "The Great Red Spot"],
              ["Q4: The planet with the most rings is ____.",
               "Neptune", "Jupiter", "Uranus", "Saturn",
               "Saturn"],
              ["Q5: What is a comet usually made of?",
               "Dust", "Snow or ice", "Both dust and snow", "None of the above",
               "Both dust and snow"],
              ["Q6: How long does it take the Earth to make one revolution around the Sun?",
               "365.25 days", "365 days", "360 days", "366 days",
               "365.25 days"],
              ["Q7: Which of the following is considered a dwarf planet in our solar system?",
               "Mercury", "Mars", "Earth", "Pluto",
               "Pluto"],
              ["Q8: Which is the smallest planet?",
               "Mercury", "Neptune", "Earth", "Saturn",
               "A55555"],
              ["Q9: The Earth is ____.",
               "Flat", "Round", "Oblate", "A lie",
               "Oblate"],
              ["Q10: Saturn is the ____ closest planet to the Sun.",
               "Third", "Fifth", "Sixteenth", "Sixth",
               "Sixth"]]

// space medium
var space2 = [["Q1: What is the name of the probe currently orbiting Jupiter?",
               "Virgil", "Juno", "Dido", "Tanit",
               "Juno"],
              ["Q2: Mars is about ____ the size of Earth.",
               "1/4th", "1/3rd", "1/6th", "1/5th",
               "1/6th"],
              ["Q3: Our universe consists primarily of ____.",
               "Star dust", "Dark matter", "Plasma", "Watermelons",
               "Dark matter"],
              ["Q4: Psyche is the ____ asteroid to be discovered.",
               "4th", "20th", "16th", "22nd",
               "16th"],
              ["Q5: The ____ have/has a strong role in the oceans' tides on Earth.",
               "Wind", "Moon", "Sun", "Sun and Moon",
               "Sun and Moon"],
              ["Q6: Pluto is unique with its ____ orbit.",
               "Near-circle", "Lunar", "Elliptical", "Poseidocentric",
               "Elliptical"],
              ["Q7: The surface of what planet looks like the surface of Earth's moon?",
               "Mercury", "Venus", "Mars", "Pluto",
               "Mercury"],
              ["Q8: Psyche is believed to be made almost entirely of:",
               "Nickel", "Iron", "Gold", "Nickel and iron",
               "Nickel and iron"],
              ["Q9: What is the primary unit of measure that scientists use to quantify the distance between galaxies?",
               "Light Years", "Astronomical Units (AU)", "Miles", "Meters",
               "Light Years"],
              ["Q10: How many countries collaborate on the International Space Station?",
               "12", "15", "17", "10",
               "15"]]

// space hard
var space3 = [["Q1: Who was the first American in space?",
               "James A Lovell, Jr.", "Buzz Aldrin", "Alan Shepard", "Gus Grissom",
               "Alan Shepard"],
              ["Q2: ____ are collapsed stars the emit repeated pulses of energy.",
               "Neutron Stars", "Dwarf Stars", "Supernova", "Pulsars",
               "Pulsars"],
              ["Q3: More than ____ Earths would fit inside Jupiter.",
               "1,300", "1,500", "1,450", "1,400",
               "1,300"],
              ["Q4: What was the name of the first mission to Pluto?",
               "Voyager I", "New Horizons", "Pioneer", "Viking",
               "New Horizons"],
              ["Q5: A/an ____ orbit is an orbit around the planet Venus.",
               "Aphrodiocentric", "Areocentric", "Heliocentric", "Jovicentric",
               "Aphrodiocentric"],
              ["Q6: Who discovered Psyche in 1852?",
               "Annibale de Gasparis", "Barnaba Oriani", "Giovanni Battista Donati", "Francesco de Vico",
               "Annibale de Gasparis"],
              ["Q7: In billions of years, when the Sun reaches the end of its life, what kind of star will it become?",
               "Compact", "Red Giant", "Quark", "Yellow Dwarf",
               "Red Giant"],
              ["Q8: What was the first planet to be discovered by telescope?",
               "Mars", "Saturn", "Uranus", "Jupiter",
               "Uranus"],
              ["Q9: What is the name of the closest galaxy to our own?",
               "Milky Way", "Whirlpool", "Triangulum", "Andromeda",
               "Andromeda"],
              ["Q10: What is the name of the black hole at the center of our galaxy?",
               "Fornax A", "Messier 105", "Sagitarrius A", "Sagitarrius B",
               "Sagitarrius A"]]

// science easy
var science1 = [["Q1: Which of the following is not a form of energy we get from the Sun?",
                 "Heat", "Kinetic", "Potential", "Light",
                 "Potential"],
                ["Q2: What is not a function of our skeletal system?",
                 "Movement", "Support", "Protection", "Digesting",
                 "Digesting"],
                ["Q3: Which of the following eats dead organic matter and puts it back into the soil?",
                 "Decomposers", "Consumers", "Scavengers", "Producers",
                 "Decomposers"],
                ["Q4: Which of the following is not a rocky planet?",
                 "Mars", "Jupiter", "Earth", "Rocky is a movie",
                 "Jupiter"],
                ["Q5: What substance or chemical is in your mouth to help soften food and begin carbohydrate digestion?",
                 "Saliva", "Water", "Blood", "Acids",
                 "Saliva"],
                ["Q6: Which form of the Sun's energy provides solar power?",
                 "Light", "Heat", "Both", "Neither",
                 "Light"],
                ["Q7: Which two chromosomes do all male humans have?",
                 "XX", "XY", "YY", "YZ",
                 "XY"],
                ["Q8: How do plants get energy?",
                 "From the soil", "Through the roots", "Through photosynthesis", "They don't need energy",
                 "Through photosynthesis"],
                ["Q9: Which of the following biomes receives the most amount of rainfall during the year?",
                 "Desert", "Tundra", "Grassland", "Forests",
                 "Forests"],
                ["Q10: What organ is in control of all other organs?",
                 "Heart", "Stomach", "Brain", "Lungs",
                 "Brain"]]

// science medium
var science2 = [["Q1: What force pulls all objects toward the center of the Earth?",
                 "Gravity", "Magnetism", "Friction", "Inertia",
                 "Gravity"],
                ["Q2: What weather tool is used to measure air pressure?",
                 "Anemometer", "Thermometer", "Barometer", "Seismometer",
                 "Barometer"],
                ["Q3: What is the part of the cell that contains the DNA and controls the cell?",
                 "Cell Wall", "Nucleus", "Cell Membrane", "Cytoplasm",
                 "Nucleus"],
                ["Q4: For humans, walking on two legs is:",
                 "An artform", "A learned behavior", "An instinct", "Necessary",
                 "An instinct"],
                ["Q5: Coprolite, fossilized scat, is considered what type of fossil?",
                 "Cast", "Mold", "Body", "Trace",
                 "Trace"],
                ["Q6: What is weight?",
                 "The same as mass", "Amount of matter in an object", "Force of gravity on an object", "I don't know",
                 "Force of gravity on an object"],
                ["Q7: Which layer of the Eart is the thinnest?",
                 "Mantle", "Crust", "Core", "They are all of equal depth",
                 "Crust"],
                ["Q8: What is the term used to describe the visible portion of the moon’s light getting smaller each night?",
                 "Crescent", "Waxing", "New", "Waning",
                 "Waning"],
                ["Q9: An example of a Carbohydrate rich food is",
                 "Cereal", "Chicken", "Watermelon", "Steak",
                 "Cereal"],
                ["Q10: What is a Calorie?",
                 "Type of fat", "Measurement of Energy", "Type of digestion", "Type of sugar",
                 "Measurement of Energy"]]

// science hard
var science3 = [["Q1: What cloud type can be described as wispy and thin?",
                 "Cumulous", "Cirrus", "Stratus", "Nimbus",
                 "Cirrus"],
                ["Q2: Which of the following bodies of water is a saltwater ecosystem?",
                 "Curie Lake", "Einstein Ocean", "Newton's Pond", "Darwin River",
                 "Einstein Ocean"],
                ["Q3: Who is credited with the discovery of DNA's double helix structure?",
                 "James Watson & Francis Crick", "Rosalind Franklin", "Raymond Gosling", "Sir Archibald Edward Garrod",
                 "James Watson & Francis Crick"],
                ["Q4: In what type of rock would you most likely find a fossil?",
                 "Volcanic", "Metamorphic", "Igneous", "Sedimentary",
                 "Sedimentary"],
                ["Q5: What warm conveyer belt of water raises the average temperature of the Easter Seaboard by as much as 15 degrees F?",
                 "Jet Stream", "Main Stream", "Gulf Stream", "Easterlie winds",
                 "Gulf Stream"],
                ["Q6: Which of the three main sources of energy provides the most calories per gram?",
                 "Fats", "Proteins", "Carbohydrates", "None provide calories",
                 "Fats"],
                ["Q7: An electric eel can produce up to __ volts of electricity.",
                 "635", "1", "670", "650",
                 "650"],
                ["Q8: True or False: Human DNA, when uncoiled, can stretch from Pluto to the Sun and back.",
                 "True", "False",
                 "True"],
                ["Q9: How fast is the average human sneeze?",
                 "80 mph", "90 mph", "100 mph", "110 mph",
                 "100 mph"],
                ["Q10: What is the average time for a plastic bottle to decompose?",
                 "500 years", "275 years", "300 years", "450 years",
                 "450 years"]]




// public var initilized
public var myDict = ["psyche1" : psyche1, "psyche2" : psyche2, "psyche3" : psyche3,
                     "nasa1" : nasa1, "nasa2" : nasa2, "nasa3" : nasa3,
                     "space1" : space1, "space2" : space2, "space3" : space3,
                     "science1" : science1, "science2" : science2, "science3" : science3]

// testing
// get psyche catagory easy difficulty array: questions/answers
let test = myDict["psyche1"]
// get psyche easy first array of array: question 1 and answers
let testOfTest = test![0]
// get psyche easy first member of first array of array: question 1
let temp = testOfTest[0]

