//
//  data+entry.swift
//  Psyche
//
//  Created by Rivinis on 3/22/18.
//  Copyright © 2018 ASU. All rights reserved.
//

import Foundation
import UIKit

// array of arrays, each has: [0] question, [1], [2] ... answers, [last element]: correct answer

// psyche easy
var psyche1 = [["Psyche is the name of a/an ____ orbiting the Sun between Mars and Jupiter.",
                "Comet", "Planet", "Asteroid", "Star",
                "3"],
               ["Psyche is the first mission to a world made of ____.",
                "Rock", "Ice", "Gas", "Metal",
                "4"],
               ["Which US University is leading this deep-space investigation?",
                "Arizona State University", "Alabama State University", "University of Arizona", "Massachusetts Institute of Technology",
                "1"],
               ["What year is the Psyche spacecraft scheduled to be launched?",
                "2020", "2022", "2026", "2023",
                "2"],
               ["True or False: Psyche, the asteroid, has an irregular shape.",
                "True", "False",
                "1"],
               ["Scientists have hypothesized that Psyche's shape was caused by:",
                "Collisions", "Gravity", "Spinning forces", "All of the above",
                "1"],
               ["What year is the spacecraft scheduled to arrive at the asteroid Psyche?",
                "2025", "2026", "2027", "2099",
                "2"],
               ["Some scientists believe that Psyche could actually be:",
                "A snowball", "A dwarf planet", "A planet's core", "A moon",
                "3"],
               ["Q9: Psyche is named after the goddess of ____ in ancient Greek mythology.",
                "The night", "The dawn", "Wisdom", "The soul",
                "4"],
               ["Q10: Who is the principal investigator of the Psyche Mission Team?",
                "Jim Bell", "Erik Asphaug", "Lindy Elkins-Tanton", "David Bercovici",
                "3"]]

// psyche medium
var psyche2 = [["When was the Psyche Mission chosen by NASA?",
                "01/04/2017", "01/02/2017", "02/03/2017", "01/30/2017",
                "1"],
               ["A year on the asteroid Psyche is equal to how many Earth years?",
                "One", "Three", "Five", "A hundred",
                "3"],
               ["The full spacecraft, including the solar panels, is about the size of a/an ____.",
                "Bowling lane", "Singles tennis court", "Football field", "Olympic swimming pool",
                "2"],
               ["Psyche is the ____ asteroid to ever be discovered.",
                "4th", "16th", "21st", "22nd",
                "2"],
               ["What year was Psyche the asteroid discovered?",
                "1864", "1896", "1910", "1852",
                "4"],
               ["What is the average distance between Psyche and the Sun in astronomical units (AU)?",
                "1 AU", "2 AU", "3 AU", "0.5 AU",
                "3"],
               ["True or False: Psyche and Earth orbit the Sun at the same speed.",
                "True", "False",
                "2"],
               ["Psyche is believed to be made almost entirely out of:",
                "Nickel", "Iron", "Gold and silver", "Nickel and iron",
                "4"],
               ["Which object is similar to Psyche in its density?",
                "A bar of steel", "A roll of aluminum foil", "A gold coin", "A German Shepherd",
                "1"],
               ["The Psyche Mission will use new communication technology to transfer data via: ",
                "Radio", "Photons", "Snapchat", "Wi-Fi",
                "2"]]

// psyche hard
var psyche3 = [["What periodic element is responsible for the solar electric propulsion that Psyche will use?",
                "Nitrogen", "Xenon", "Hydrogen", "Oxygen",
                "2"],
               ["How long is a day on Psyche?",
                "5 hours, 2 minutes", "4 hours, 12 minutes", "4 hours, 22 minutes", "3 hours, 57 minutes",
                "2"],
               ["Who discovered Psyche in 1852?",
                "Annibale de Gasparis", "Barnaba Oriani", "Giovanni Battista Donati", "Francesco de Vico",
                "A1"],
               ["When did NASA have evidence that confirmed Psyche's metal composition?",
                "2008", "2012", "2011", "2010",
                "4"],
               ["What company is building the solar-electric propulsion chassis?",
                "General Dynamics", "Tesat Spacecom", "Space Systems Loral", "Malin Space Science Systems",
                "3"],
               ["The Psyche Mission will use a/an ____ telecommunications system to measure Psyche's gravity field.",
                "X-band Radio", "P25 Radio", "Optical", "High-rate RF",
                "1"],
               ["The team responsible for developing the Psyche Gamma Ray and Neutron Spectrometer is based at:",
                "Massachusetts Institute of Technology", "University of California", "Southwest Research Institute", "Johns Hopkins University",
                "3"],
               ["If Psyche were a perfect sphere, it would have a surface area approximately the size of:",
                "Texas", "California", "Montana", "Alaska",
                "1"],
               ["How much mass of the Asteroid Belt does Psyche represent?",
                "0.50%", "3%", "1%", "5%",
                "3"],
               ["The Psyche Mission total cost (development, operations, and science) is estimated to be about:",
                "$600 Million", "$775 Million", "$950 Million", "$850 Million",
                "4"]]

// nasa easy
var nasa1 = [["From 1957 to 1975, the United States competed primarily with what country in the Space Race?",
              "China", "Soviet Union (USSR)", "Cuba", "Germany",
              "2"],
             ["What was the name of the successful NASA Mission to the moon?",
              "Mercury Program", "Apollo 11", "Mission Impossible", "Project Vanguard",
              "2"],
             ["Which space vehicle is used to carry astronauts to space and back?",
              "Space Shuttle", "Rocket", "Launch Vehicle", "Satellite",
              "1"],
             ["Earth is the only planet where ____ is known to exist.",
              "Weather", "Air", "Water", "Life",
              "4"],
             ["A ____ is an object that moves around a larger object.",
              "Probe", "Moon", "Satellite", "Telescope",
              "3"],
             ["What is the name of the largest telescope currently orbiting Earth?",
              "Hubble", "Bubble", "Gaia", "Astrosat",
              "1"],
             ["A supernova is the ____ of a star.",
              "Nebula or Birth", "Cooling", "Main Sequence", "Death explosion",
              "4"],
             ["Who was the first United States' female astronaut?",
              "Sally Ride", "Kathryn Sullivan", "Mae Jemison", "Peggy Whitson",
              "1"],
             ["Where is Psyche the Asteroid located?",
              "Outside the Solar System", "Between Venus and Earth", "In the Asteroid Belt", "Orbiting Jupiter",
              "3"],
             ["Psyche is the first mission to a world made of _____.",
              "Rock", "Ice", "Candy", "Metal",
              "4"]]

// nasa medium
var nasa2 = [["What is the name of the satellite currently orbiting Jupiter?",
              "Virgil", "Juno", "Dido", "Tanit",
              "2"],
             ["Which program helped prepare NASA to land on the moon?",
              "Ranger Program", "Project Mercury", "Gemini Program", "Mercury Program",
              "3"],
             ["Planet Earth is also known to scientists as the ____ planet.",
              "Best", "Home", "Live", "Goldilocks",
              "4"],
             ["True or False: the Earth is not a perfect sphere.",
              "True", "False",
              "1"],
             ["The number of meteorites found in ____ is equal to the number of meteorites found in the rest of the world combined.",
              "North America", "Asia", "Africa", "Antartica",
              "4"],
             ["What year was the Hubble Space Telescope launched into orbit?",
              "1993", "1983", "1990", "1997",
              "3"],
             ["NASA was created in what year?",
              "1957", "1958", "1955", "1956",
              "2"],
             ["What year is the spacecraft scheduled to arrive at Psyche the asteroid?",
              "2025", "2028", "2027", "2026",
              "4"],
             ["What is the highest number of women that have been in space together at once?",
              "4", "3", "5", "2",
              "1"],
             ["True or False: You can see Earth's round shadow on the moon during a lunar eclipse.",
              "True", "True",
              "1"]]

// nasa hard
var nasa3 = [["Who was the first American in space?",
              "James A Lovell, Jr.", "Buzz Aldrin", "Alan Shepard", "Gus Grissom",
              "3"],
             ["What was the name of the NASA Rocket that launched humans to the moon?",
              "Delta G", "Thor-Delta", "Scout", "Saturn V",
              "4"],
             ["True or False: with GPS and satellites, scientists can measure Earth's size and shape to within a millimeter.",
              "True", "False",
              "2"],
             ["What company is partnered with NASA to develop the Robonaut?",
              "Space Systems Loral", "General Motors", "General Dynamics", "Tesat Spacecom",
              "2"],
             ["Hubble transmits ____ gigabytes of science data each week back to Earth.",
              "140", "150", "120", "175",
              "1"],
             ["NASA uses solar eclipses as an opportunity to study the sun's ___.",
              "Corona", "Chromosphere", "Core", "All of the above",
              "1"],
             ["As of this April 2018, how many women have been in space?",
              "58", "60", "63", "57",
              "2"],
             ["Katherine Johnson's first task on the space team was to calculate the ____ for the rocket that would put the first American in space.",
              "Thrust", "Fuel Required", "Flight Path", "Altitude",
              "3"],
             ["Where is the Psyche Spacecraft scheduled to launch from?",
              "Goddard Space Flight Center", "Wallops Flight Facility", "Marshall Space Flight Center", "Kennedy Space Center",
              "4"],
             ["Who is the current NASA Administrator?",
              "Steve Jurczyk", "Krista Baquin", "Robert M Lightfoot, Jr.", "Thomas Cremins",
              "3"]]

// space easy
var space1 = [["What is the hottest planet in the solar system?",
               "Earth", "Venus", "Saturn", "Neptune",
               "2"],
              ["What was the name of the successful NASA Mission to the moon?",
               "Mercury Program", "Apollo 11", "Ranger Program", "Project Vanguard",
               "2"],
              ["One of Jupiter's most famous features is ____.",
               "The Great Red Spot", "An icy surface", "Plant life", "its love for rock music",
               "1"],
              ["The planet with the most rings is ____.",
               "Neptune", "Jupiter", "Uranus", "Saturn",
               "4"],
              ["What is a comet usually made of?",
               "Dust", "Snow or ice", "Both dust and snow", "None of the above",
               "3"],
              ["How long does it take the Earth to make one revolution around the Sun?",
               "365.25 days", "365 days", "360 days", "366 days",
               "1"],
              ["Which of the following is considered a dwarf planet in our solar system?",
               "Mercury", "Mars", "Earth", "Pluto",
               "4"],
              ["Which is the smallest planet?",
               "Mercury", "Neptune", "Earth", "Saturn",
               "1"],
              ["The Earth is ____.",
               "Flat", "Round", "Oblate", "A lie",
               "3"],
              ["Saturn is the ____ closest planet to the Sun.",
               "Third", "Fifth", "Sixteenth", "Sixth",
               "4"]]

// space medium
var space2 = [["What is the name of the probe currently orbiting Jupiter?",
               "Virgil", "Juno", "Dido", "Tanit",
               "Juno"],
              ["Mars is about ____ the size of Earth.",
               "1/4th", "1/3rd", "1/6th", "1/5th",
               "1/6th"],
              ["Our universe consists primarily of ____.",
               "Star dust", "Dark matter", "Plasma", "Watermelons",
               "Dark matter"],
              ["Psyche is the ____ asteroid to be discovered.",
               "4th", "20th", "16th", "22nd",
               "16th"],
              ["The ____ have/has a strong role in the oceans' tides on Earth.",
               "Wind", "Moon", "Sun", "Sun and Moon",
               "Sun and Moon"],
              ["Pluto is unique with its ____ orbit.",
               "Near-circle", "Lunar", "Elliptical", "Poseidocentric",
               "Elliptical"],
              ["The surface of what planet looks like the surface of Earth's moon?",
               "Mercury", "Venus", "Mars", "Pluto",
               "Mercury"],
              ["Psyche is believed to be made almost entirely of:",
               "Nickel", "Iron", "Gold", "Nickel and iron",
               "Nickel and iron"],
              ["What is the primary unit of measure that scientists use to quantify the distance between galaxies?",
               "Light Years", "Astronomical Units (AU)", "Miles", "Meters",
               "Light Years"],
              ["How many countries collaborate on the International Space Station?",
               "12", "15", "17", "10",
               "2"]]

// space hard
var space3 = [["Who was the first American in space?",
               "James A Lovell, Jr.", "Buzz Aldrin", "Alan Shepard", "Gus Grissom",
               "3"],
              ["____ are collapsed stars the emit repeated pulses of energy.",
               "Neutron Stars", "Dwarf Stars", "Supernova", "Pulsars",
               "4"],
              ["More than ____ Earths would fit inside Jupiter.",
               "1,300", "1,500", "1,450", "1,400",
               "1"],
              ["What was the name of the first mission to Pluto?",
               "Voyager I", "New Horizons", "Pioneer", "Viking",
               "2"],
              ["A/an ____ orbit is an orbit around the planet Venus.",
               "Aphrodiocentric", "Areocentric", "Heliocentric", "Jovicentric",
               "1"],
              ["Who discovered Psyche in 1852?",
               "Annibale de Gasparis", "Barnaba Oriani", "Giovanni Battista Donati", "Francesco de Vico",
               "1"],
              ["In billions of years, when the Sun reaches the end of its life, what kind of star will it become?",
               "Compact", "Red Giant", "Quark", "Yellow Dwarf",
               "2"],
              ["What was the first planet to be discovered by telescope?",
               "Mars", "Saturn", "Uranus", "Jupiter",
               "3"],
              ["What is the name of the closest galaxy to our own?",
               "Milky Way", "Whirlpool", "Triangulum", "Andromeda",
               "4"],
              ["What is the name of the black hole at the center of our galaxy?",
               "Fornax A", "Messier 105", "Sagitarrius A", "Sagitarrius B",
               "3"]]

// science easy
var science1 = [["Which of the following is not a form of energy we get from the Sun?",
                 "Heat", "Kinetic", "Potential", "Light",
                 "3"],
                ["What is not a function of our skeletal system?",
                 "Movement", "Support", "Protection", "Digesting",
                 "4"],
                ["Which of the following eats dead organic matter and puts it back into the soil?",
                 "Decomposers", "Consumers", "Scavengers", "Producers",
                 "1"],
                ["Which of the following is not a rocky planet?",
                 "Mars", "Jupiter", "Earth", "Rocky is a movie",
                 "2"],
                ["What substance or chemical is in your mouth to help soften food and begin carbohydrate digestion?",
                 "Saliva", "Water", "Blood", "Acids",
                 "1"],
                ["Which form of the Sun's energy provides solar power?",
                 "Light", "Heat", "Both", "Neither",
                 "1"],
                ["Which two chromosomes do all male humans have?",
                 "XX", "XY", "YY", "YZ",
                 "2"],
                ["How do plants get energy?",
                 "From the soil", "Through the roots", "Through photosynthesis", "They don't need energy",
                 "3"],
                ["Which of the following biomes receives the most amount of rainfall during the year?",
                 "Desert", "Tundra", "Grassland", "Forests",
                 "4"],
                ["What organ is in control of all other organs?",
                 "Heart", "Stomach", "Brain", "Lungs",
                 "3"]]

// science medium
var science2 = [["What force pulls all objects toward the center of the Earth?",
                 "Gravity", "Magnetism", "Friction", "Inertia",
                 "1"],
                ["What weather tool is used to measure air pressure?",
                 "Anemometer", "Thermometer", "Barometer", "Seismometer",
                 "3"],
                ["What is the part of the cell that contains the DNA and controls the cell?",
                 "Cell Wall", "Nucleus", "Cell Membrane", "Cytoplasm",
                 "2"],
                ["For humans, walking on two legs is:",
                 "An artform", "A learned behavior", "An instinct", "Necessary",
                 "3"],
                ["Coprolite, fossilized scat, is considered what type of fossil?",
                 "Cast", "Mold", "Body", "Trace",
                 "4"],
                ["What is weight?",
                 "The same as mass", "Amount of matter in an object", "Force of gravity on an object", "I don't know",
                 "3"],
                ["Which layer of the Eart is the thinnest?",
                 "Mantle", "Crust", "Core", "They are all of equal depth",
                 "2"],
                ["What is the term used to describe the visible portion of the moon’s light getting smaller each night?",
                 "Crescent", "Waxing", "New", "Waning",
                 "4"],
                ["An example of a Carbohydrate rich food is",
                 "Cereal", "Chicken", "Watermelon", "Steak",
                 "1"],
                ["What is a Calorie?",
                 "Type of fat", "Measurement of Energy", "Type of digestion", "Type of sugar",
                 "2"]]

// science hard
var science3 = [["What cloud type can be described as wispy and thin?",
                 "Cumulous", "Cirrus", "Stratus", "Nimbus",
                 "2"],
                ["Which of the following bodies of water is a saltwater ecosystem?",
                 "Curie Lake", "Einstein Ocean", "Newton's Pond", "Darwin River",
                 "2"],
                ["Who is credited with the discovery of DNA's double helix structure?",
                 "James Watson & Francis Crick", "Rosalind Franklin", "Raymond Gosling", "Sir Archibald Edward Garrod",
                 "1"],
                ["In what type of rock would you most likely find a fossil?",
                 "Volcanic", "Metamorphic", "Igneous", "Sedimentary",
                 "4"],
                ["What warm conveyer belt of water raises the average temperature of the Easter Seaboard by as much as 15 degrees F?",
                 "Jet Stream", "Main Stream", "Gulf Stream", "Easterlie winds",
                 "3"],
                ["Which of the three main sources of energy provides the most calories per gram?",
                 "Fats", "Proteins", "Carbohydrates", "None provide calories",
                 "1"],
                ["An electric eel can produce up to __ volts of electricity.",
                 "635", "1", "670", "650",
                 "4"],
                ["True or False: Human DNA, when uncoiled, can stretch from Pluto to the Sun and back.",
                 "True", "False",
                 "1"],
                ["How fast is the average human sneeze?",
                 "80 mph", "90 mph", "100 mph", "110 mph",
                 "3"],
                ["What is the average time for a plastic bottle to decompose?",
                 "500 years", "275 years", "300 years", "450 years",
                 "4"]]




// public var initilized
public var myDict = ["psyche1" : psyche1, "psyche2" : psyche2, "psyche3" : psyche3, "psyche4" : psyche3,
                     "nasa1" : nasa1, "nasa2" : nasa2, "nasa3" : nasa3, "nasa4" : nasa3,
                     "space1" : space1, "space2" : space2, "space3" : space3,"space4" : space3,
                     "science1" : science1, "science2" : science2, "science3" : science3, "science4" : science3]

// testing
// get psyche catagory easy difficulty array: questions/answers
let test = myDict["psyche1"]
// get psyche easy first array of array: question 1 and answers
let testOfTest = test![0]
// get psyche easy first member of first array of array: question 1
let temp = testOfTest[0]

