//
//  data+entry.swift
//  Psyche
//
//  Created by Rivinis on 3/22/18.
//  Copyright © 2018 ASU. All rights reserved.
//

import Foundation
import UIKit

// array of arrays, each has: [0] question, [1], [2] ... answers, [last element]: correct answer

// psyche easy
var psyche1 = [["Q1: Psyche is the name of a/an ____ orbiting the Sun between Mars and Jupiter.",
                "Comet", "Planet", "Asteroid", "Star",
                "Asteroid"],
               ["Q2: Psyche is the first mission to a world made of ____.",
                "Rock", "Ice", "Gas", "Metal",
                "Metal"],
               ["Q3: Which US University is leading this deep-space investigation?",
                "Arizona State University", "Alabama State University", "University of Arizona", "Massachusetts Institute of Technology",
                "Arizona State University"],
               ["Q4: What year is the Psyche spacecraft scheduled to be launched?",
                "2020", "2022", "2026", "2023",
                "2022"],
               ["Q5: True or False: Psyche, the asteroid, has an irregular shape.",
                "True", "False",
                "True"],
               ["Q6: Scientists have hypothesized that Psyche's shape was caused by:",
                "Collisions", "Gravity", "Spinning forces", "All of the above",
                "Collisions"],
               ["Q7: What year is the spacecraft scheduled to arrive at the asteroid Psyche?",
                "2025", "2026", "2027", "2099",
                "2026"],
               ["Q8: Some scientists believe that Psyche could actually be:",
                "A snowball", "A dwarf planet", "A planet's core", "A moon",
                "A planet's core"],
               ["Q9: Psyche is named after the goddess of ____ in ancient Greek mythology.",
                "The night", "The dawn", "Wisdom", "The soul",
                "The soul"],
               ["Q10: Who is the principal investigator of the Psyche Mission Team?",
                "Jim Bell", "Erik Asphaug", "Lindy Elkins-Tanton", "David Bercovici",
                "Lindy Elkins-Tanton"]]

// psyche medium
var psyche2 = [["Q1: When was the Psyche Mission chosen by NASA?",
                "01/04/2017", "01/02/2017", "02/03/2017", "01/30/2017",
                "01/04/2017"],
               ["Q2: A year on the asteroid Psyche is equal to how many Earth years?",
                "One", "Three", "Five", "A hundred",
                "Five"],
               ["Q3: The full spacecraft, including the solar panels, is about the size of a/an ____.",
                "Bowling lane", "Singles tennis court", "Football field", "Olympic swimming pool",
                "Singles tennis court"],
               ["Q4: Psyche is the ____ asteroid to ever be discovered.",
                "4th", "16th", "21st", "22nd",
                "16th"],
               ["Q5: What year was Psyche the asteroid discovered?",
                "1864", "1896", "1910", "1852",
                "1852"],
               ["Q6: What is the average distance between Psyche and the Sun in astronomical units (AU)?",
                "1 AU", "2 AU", "3 AU", "0.5 AU",
                "3 AU"],
               ["Q7: True or False: Psyche and Earth orbit the Sun at the same speed.",
                "True", "False",
                "False"],
               ["Q8: Psyche is believed to be made almost entirely out of:",
                "Nickel", "Iron", "Gold and silver", "Nickel and iron",
                "Nickel and iron"],
               ["Q9: Which object is similar to Psyche in its density?",
                "A bar of steel", "A roll of aluminum foil", "A gold coin", "A German Shepherd",
                "A bar of steel"],
               ["Q10: The Psyche Mission will use new communication technology to transfer data via: ",
                "Radio", "Photons", "Snapchat", "Wi-Fi",
                "Photons"]]

// psyche hard
var psyche3 = [["Q1: What periodic element is responsible for the solar electric propulsion that Psyche will use?",
                "Nitrogen", "Xenon", "Hydrogen", "Oxygen",
                "Xenon"],
               ["Q2: How long is a day on Psyche?",
                "5 hours, 2 minutes", "4 hours, 12 minutes", "4 hours, 22 minutes", "3 hours, 57 minutes",
                "4 hours, 12 minutes"],
               ["Q3: Who discovered Psyche in 1852?",
                "Annibale de Gasparis", "Barnaba Oriani", "Giovanni Battista Donati", "Francesco de Vico",
                "Annibale de Gasparis"],
               ["Q4: When did NASA have evidence that confirmed Psyche's metal composition?",
                "2008", "2012", "2011", "2010",
                "2010"],
               ["Q5: What company is building the solar-electric propulsion chassis?",
                "General Dynamics", "Tesat Spacecom", "Space Systems Loral", "Malin Space Science Systems",
                "Space Systems Loral"],
               ["Q6: The Psyche Mission will use a/an ____ telecommunications system to measure Psyche's gravity field.",
                "X-band Radio", "P25 Radio", "Optical", "High-rate RF",
                "X-band Radio"],
               ["Q7: The team responsible for developing the Psyche Gamma Ray and Neutron Spectrometer is based at:",
                "Massachusetts Institute of Technology", "University of California", "Southwest Research Institute", "Johns Hopkins University",
                "Johns Hopkins University"],
               ["Q8: If Psyche were a perfect sphere, it would have a surface area approximately the size of:",
                "Texas", "California", "Montana", "Alaska",
                "Texas"],
               ["Q9: How much mass of the Asteroid Belt does Psyche represent?",
                "0.50%", "3%", "1%", "5%",
                "1%"],
               ["Q10: The Psyche Mission total cost (development, operations, and science) is estimated to be about:",
                "$600 Million", "$775 Million", "$950 Million", "$850 Million",
                "$850 Million"]]

// nasa easy
var nasa1 = [["Q1: From 1957 to 1975, the United States competed primarily with what country in the Space Race?",
              "China", "Soviet Union (USSR)", "Cuba", "Germany",
              "Soviet Union (USSR)"],
             ["Q2: What was the name of the successful NASA Mission to the moon?",
              "Mercury Program", "Apollo 11", "Mission Impossible", "Project Vanguard",
              "Apollo 11"],
             ["Q3: Which space vehicle is used to carry astronauts to space and back?",
              "Space Shuttle", "Rocket", "Launch Vehicle", "Satellite",
              "Space Shuttle"],
             ["Q4: Earth is the only planet where ____ is known to exist.",
              "Weather", "Air", "Water", "Life",
              "Life"],
             ["Q5: A ____ is an object that moves around a larger object.",
              "Probe", "Moon", "Satellite", "Telescope",
              "Satellite"],
             ["Q6: What is the name of the largest telescope currently orbiting Earth?",
              "Hubble", "Bubble", "Gaia", "Astrosat",
              "Hubble"],
             ["Q7: A supernova is the ____ of a star.",
              "Nebula or Birth", "Cooling", "Main Sequence", "Death explosion",
              "Death explosion"],
             ["Q8: Who was the first United States' female astronaut?",
              "Sally Ride", "Kathryn Sullivan", "Mae Jemison", "Peggy Whitson",
              "Sally Ride"],
             ["Q9: Where is Psyche the Asteroid located?",
              "Outside the Solar System", "Between Venus and Earth", "In the Asteroid Belt", "Orbiting Jupiter",
              "In the Asteroid Belt"],
             ["Q10: Psyche is the first mission to a world made of _____.",
              "Rock", "Ice", "Candy", "Metal",
              "Metal"]]

// nasa medium
var nasa2 = [["Q1: What is the name of the satellite currently orbiting Jupiter?",
              "Virgil", "Juno", "Dido", "Tanit",
              "Juno"],
             ["Q2: Which program helped prepare NASA to land on the moon?",
              "Ranger Program", "Project Mercury", "Gemini Program", "Mercury Program",
              "Gemini Program"],
             ["Q3: Planet Earth is also known to scientists as the ____ planet.",
              "Best", "Home", "Live", "Goldilocks",
              "Goldilocks"],
             ["Q4: True or False: the Earth is not a perfect sphere.",
              "True", "False",
              "True"],
             ["Q5: The number of meteorites found in ____ is equal to the number of meteorites found in the rest of the world combined.",
              "North America", "Asia", "Africa", "Antartica",
              "Antartica"],
             ["Q6: What year was the Hubble Space Telescope launched into orbit?",
              "1993", "1983", "1990", "1997",
              "1990"],
             ["Q7: NASA was created in what year?",
              "1957", "1958", "1955", "1956",
              "1958"],
             ["Q8: What year is the spacecraft scheduled to arrive at Psyche the asteroid?",
              "2025", "2028", "2027", "2026",
              "A55555"],
             ["Q9: What is the highest number of women that have been in space together at once?",
              "4", "3", "5", "2",
              "4"],
             ["Q10: True or False: You can see Earth's round shadow on the moon during a lunar eclipse.",
              "True", "True",
              "True"]]

// nasa hard
var nasa3 = [["Q1: Who was the first American in space?",
              "James A Lovell, Jr.", "Buzz Aldrin", "Alan Shepard", "Gus Grissom",
              "Alan Shepard"],
             ["Q2: What was the name of the NASA Rocket that launched humans to the moon?",
              "Delta G", "Thor-Delta", "Scout", "Saturn V",
              "Saturn V"],
             ["Q3: True or False: with GPS and satellites, scientists can measure Earth's size and shape to within a millimeter.",
              "True", "False",
              "False"],
             ["Q4: ",
              "A11111", "A22222", "A33333", "A44444",
              "A55555"],
             ["Q5: ",
              "A11111", "A22222", "A33333", "A44444",
              "A55555"],
             ["Q6: ",
              "A11111", "A22222", "A33333", "A44444",
              "A55555"],
             ["Q7: ",
              "A11111", "A22222", "A33333", "A44444",
              "A55555"],
             ["Q8: ",
              "A11111", "A22222", "A33333", "A44444",
              "A55555"],
             ["Q9: ",
              "A11111", "A22222", "A33333", "A44444",
              "A55555"],
             ["Q10: ",
              "A11111", "A22222", "A33333", "A44444",
              "A55555"]]

// nasa hard
var nasa4 = [["Q1: ",
              "A11111", "A22222", "A33333", "A44444",
              "A55555"],
             ["Q2: ",
              "A11111", "A22222", "A33333", "A44444",
              "A55555"],
             ["Q3: ",
              "A11111", "A22222", "A33333", "A44444",
              "A55555"],
             ["Q4: ",
              "A11111", "A22222", "A33333", "A44444",
              "A55555"],
             ["Q5: ",
              "A11111", "A22222", "A33333", "A44444",
              "A55555"],
             ["Q6: ",
              "A11111", "A22222", "A33333", "A44444",
              "A55555"],
             ["Q7: ",
              "A11111", "A22222", "A33333", "A44444",
              "A55555"],
             ["Q8: ",
              "A11111", "A22222", "A33333", "A44444",
              "A55555"],
             ["Q9: ",
              "A11111", "A22222", "A33333", "A44444",
              "A55555"],
             ["Q10: ",
              "A11111", "A22222", "A33333", "A44444",
              "A55555"]]


// public var initilized
public var myDict = ["psyche1" : psyche1]

// testing
// get psyche catagory easy difficulty array: questions/answers
let test = myDict["psyche1"]
// get psyche easy first array of array: question 1 and answers
let testOfTest = test![0]
// get psyche easy first member of first array of array: question 1
let temp = testOfTest[0]




